### ISSUE TITLE
Differentiate radio & checkbox

### ISSUE THREAD

**Issue by 0rsa** [fntneves/jquery-labelauty#11]
Hello,

Thank you for your awesome plugin.

I was just annoyed because you cannot differentiate radio elements and checkbox elements out of the box.

I edited the create function to add a new parameter "type" :

    function create( input_id, messages_object, label, type )

And the line which is calling this function with the type of the current element :

    $object.after( create( input_id, labels_object, use_labels, $object.attr("type") ) );

And finally I added a custom class to the label markup : 

    block = '<label class="customClassFor'+type+'" for="' + input_id + '">' +

I can now apply a different styling for radio or checkbox (circle radio and square checkbox for example)

Maybe it could help somebody.

**Comment by fntneves** [comment]
Hello,

Thank you for your issue.

Actually, it's really interesting your issue. You're giving ideas for next version, currently under development. Thank you, again !

An alternative for this version, without changing the source code is by using CSS. Look at this:

```css
input[type="checkbox"].labelauty + label
{
 /* your style here for checkboxes */
}
```

**Comment by 0rsa** [comment]
Oh yeah, I've learnt one thing today, thank you :+1:

**Comment by fntneves** [comment]
You're welcome. Keep learning :+1:
