### ISSUE TITLE
Doesn't work if your radio buttons have ids

### ISSUE THREAD

**Issue by barriestewart** [fntneves/jquery-labelauty#12]
The plugin doesn't work on radio buttons that have ids set. Usually I wouldn't set ids on radio buttons but ASP.NET MVC does this automatically. It's quite easily fixed by changing this line:

    if( input_id == null )

To this:

    if( input_id == null || $object.is(':radio') )

**Comment by fntneves** [comment]
That condition is used when input doesn't have an ID, so a random one wil be generated. It's weird if it's not working when there's a custom ID.

Do you know which ID caused this issue ? Can you create a jsfiddle for this issue ?

**Comment by barriestewart** [comment]
Sure I've created a crude jsfiddle [here](http://jsfiddle.net/6nnmk6bk/).

The main issue here is really how MVC is generating the same id for each of these fields. I can work around that by getting MVC to set the id attribute to something unique like `Guid.NewGuid()` which means I don't have to touch your code. I had initially tried getting it to generate with blank ids too which still causes the same issue.

**Comment by fntneves** [comment]
Ok, got it.

For the first problem, a new option that forces the ID replacement may fix it. It's a new **feature**.

The blank ID is a **bug**, so I will fix it asap.
