### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by netbandit** [fntneves/jquery-labelauty#21]
Hey there,

great component - i had a quick question regarding changing colors of individual checkboxes.. is there a way to do that? I dont want them all to be the same color - but varied.. is there a way to do that? 

thanks

**Comment by fntneves** [comment]
You can add individual classes using the `class` property and instantiate the plugin on specific classes, also.

If you need an example, I can provide you one.

However, it is something to definitely improve.

Thank you.
