### ISSUE TITLE
Could you please fix this plugin to support IE8？

### ISSUE THREAD

**Issue by mengxin-FE** [fntneves/jquery-labelauty#26]
Could you please fix this plugin to support IE8？or tell me how to modify and support. 
Thanks a lot!

**Comment by mengxin-FE** [comment]
Hi,
   I used this plugin,In chrome,It looks like this,prefect!
![qq 20170731114355](https://user-images.githubusercontent.com/14139852/28761993-982be10c-75e5-11e7-8e9a-179b1be91e3b.png)
   and,In IE8,It looks like this,maybe have some problem and I don't know why,DOM Node might haven't render.Is the <label> doesn't support IE8?
![qq 20170731114403](https://user-images.githubusercontent.com/14139852/28762123-8cc0f8f6-75e6-11e7-9a5f-f0337c0a4c57.png)

**Comment by MUCHZER** [comment]
Did you tried using polyfills ?

**Comment by mengxin-FE** [comment]
sorry,I don't know where the plugin doesn't support in IE8

**Comment by MUCHZER** [comment]
jQuery is only support in IE9, the last jQuery version supported by IE8 is jQuery 1.11.3
https://jquery.com/browser-support/

**Comment by mengxin-FE** [comment]
Thanks for your answer,In my project,I used jQuery "1.9.1".
In jquery-labelauty.js, Line 25，`class: "labelauty",`   IE8 think it's  has some problem,
![qq 20170801170732](https://user-images.githubusercontent.com/14139852/28817931-4d94bb30-76dc-11e7-8589-090cf6fd6e4d.png)

And,In IE8,Call plugin has some problem，$(":checkbox").labelauty();

I modify jquery-labelauty.js code line 25 : `class: "labelauty" >"class": "labelauty"`  , 
line 87 : `$object.addClass(settings.class);` > $object.addClass(settings["class"]);
and IE8 doesn't report an error。

![qq 20170801172050](https://user-images.githubusercontent.com/14139852/28818474-d532b1c2-76dd-11e7-9778-11080ac8a7ff.png)

Look forward to your reply.  Thank you！

**Comment by MUCHZER** [comment]
So it's working with your tweaks ?

**Comment by fntneves** [comment]
Please check 1.1.4 release and see if it is now solved.
