### ISSUE TITLE
Please tag your releases

### ISSUE THREAD

**Issue by DavidAnderson684** [fntneves/jquery-labelauty#27]
Hi,

Thank you for this project. Please can you tag your releases, so that they're easier for users to track? https://github.com/fntneves/jquery-labelauty/releases shows a most-recent release of 1.1.0, which is what then shows up in tools tracking Github. But your commit log shows that you have designated subsequent points in the tree as 1.1.1, 1.1.2, 1.1.3.

David

**Comment by fntneves** [comment]
Hello,

Thank your for your issue.
It is now resolved.
